### ISSUE TITLE
How to generate 4D data from a custom video

### ISSUE THREAD

**Issue by BilendM** [zeng-yifei/STAG4D#14]
Sorry to bother you, but I wasn't sure on how to generate 4D from a custom video. Based on the Readme, I should do the following:

```
To generate the spatial-temporal consistent data from stratch, your should place your rgba data in the form of

├── dataset
│   | your_data 
│     ├── 0_rgba.png
│     ├── 1_rgba.png
│     ├── 2_rgba.png
│     ├── ...

```

Is there any specific way I should turn my video into rgba data?

Thank you for the support! 🫶

**Comment by BilendM** [comment]
I used the following script to generate rgba data from a gif if it might prove useful for anyone :)

```
import os
from PIL import Image

def convert_gif_to_rgba(gif_path, output_folder):
    with Image.open(gif_path) as img:
        for frame in range(img.n_frames):
            img.seek(frame)
            rgba_img = img.convert("RGBA")
            rgba_img.save(os.path.join(output_folder, f"{frame}_rgba.png"))

gif_path = "panda.gif"
output_folder = "panda"
os.makedirs(output_folder, exist_ok=True)
convert_gif_to_rgba(gif_path, output_folder)

```

**Comment by zeng-yifei** [comment]
I recommend using [Track-Anything](https://github.com/gaomingqi/Track-Anything) to create the frames with transparent channels. By slightly modifying its code, you can then easily turn any video into rgba images after selecting the object.
