### ISSUE TITLE
Why use Hexplane instead of MLPs for the dynamics modeling?

### ISSUE THREAD

**Issue by yifliu3** [zeng-yifei/STAG4D#18]

**Comment by zeng-yifei** [comment]
Hexplane is more stable to train from my experience. SDS has large variations in gradients. As a result, a representation like Hexplane is easier to converge intuitively as it has a kind of continuous features.

Besides, for scenes have relatively small motions, you can interpolate through time to get a slow-motion effect after training, which can be really fun.

**Comment by yifliu3** [comment]
Got it. Thanks a lot for your reply!
