### ISSUE TITLE
The azimuth used in the test datasets

### ISSUE THREAD

**Issue by wusar** [zeng-yifei/STAG4D#20]
First of all, thank you for your great work! 

I am running the evaluation on the Consistent4D evaluation dataset: https://github.com/yanqinJiang/Consistent4D/.I have a question regarding the testing setup used in your project. Could you please provide the azimuth and elevation values you used during testing?

Additionally, if possible, could you share the code for performing the tests or rendering the views for testing?

Thank you for your time and help!

**Comment by zeng-yifei** [comment]
The script and setting for the evaluation are the same as Consistent4D except that we use 30 frames for evaluation.  We provide the data used for the test in #10 . You can refer to this issue for details.

**Comment by wusar** [comment]
Thanks! I have found the view in Consistent4D_data , I will close the issue.
